/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.seanabraham;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        App app = new App();
        System.out.println(app.getGreeting());
    }

    public void doAThing() {
      System.out.println("Doing a thing!");
      System.exit(0);
    }
}
